### ISSUE TITLE
Make library work on OSX

### ISSUE THREAD

**Issue by rustomax** [mrhdias/nim-libgd#1]
Great work on `nim-libgd`! I've tested this library on OSX and it works. The only adjustment that needs to be made is the procedure definition pragmas in `libgd.nim` should reference `libgd.dylib` library name instead of `libgd.so`, for instance
```nim
proc gdImageCreate(sx: cint; sy: cint): gdImagePtr {.cdecl, importc: "gdImageCreate", dynlib: "libgd.dylib".}
```
Could you write a compile-time check for this that injects appropriate library name?

Additionally `brew install libgd` will get the C library installed on OSX.

**Comment by rustomax** [comment]
See PR [#2]

**Comment by mrhdias** [comment]
Thank you for your help. I already committed the pull request.
